train_data_file: data/train_data.csv
val_data_file: data/val_data.csv
tf_idf_vectorizer: vectorizers/Tf_IFD_vectorizer.pkl
word2vec_tokenizer: vectorizers/tokenizer_word2vec.pkl
maxlen_tfidf: 200
maxlen_word2vec: 700
